export const contentViews = [
  {
    id: 20871543,
    courseRegistrationId: 1100977,
    courseContentId: 1,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: 1,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 1,
  },
  {
    id: 20871562,
    courseRegistrationId: 1100977,
    courseContentId: 2,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 2,
  },
  {
    id: 20871561,
    courseRegistrationId: 1100977,
    courseContentId: 3,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 3,
  },
  {
    id: 20871560,
    courseRegistrationId: 1100977,
    courseContentId: 4,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 4,
  },
  {
    id: 20871559,
    courseRegistrationId: 1100977,
    courseContentId: 5,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 5,
  },
  {
    id: 20871558,
    courseRegistrationId: 1100977,
    courseContentId: 6,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 6,
  },
  {
    id: 20871557,
    courseRegistrationId: 1100977,
    courseContentId: 7,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 7,
  },
  {
    id: 20871556,
    courseRegistrationId: 1100977,
    courseContentId: 8,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 8,
  },
  {
    id: 20871555,
    courseRegistrationId: 1100977,
    courseContentId: 9,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 9,
  },
  {
    id: 20871554,
    courseRegistrationId: 1100977,
    courseContentId: 10,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 10,
  },
  {
    id: 20871553,
    courseRegistrationId: 1100977,
    courseContentId: 11,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 11,
  },
  {
    id: 20871552,
    courseRegistrationId: 1100977,
    courseContentId: 12,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 12,
  },
  {
    id: 20871551,
    courseRegistrationId: 1100977,
    courseContentId: 13,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 13,
  },
  {
    id: 20871550,
    courseRegistrationId: 1100977,
    courseContentId: 14,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 14,
  },
  {
    id: 20871549,
    courseRegistrationId: 1100977,
    courseContentId: 15,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 15,
  },
  {
    id: 20871548,
    courseRegistrationId: 1100977,
    courseContentId: 16,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 16,
  },
  {
    id: 20871547,
    courseRegistrationId: 1100977,
    courseContentId: 17,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 17,
  },
  {
    id: 20871546,
    courseRegistrationId: 1100977,
    courseContentId: 18,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 18,
  },
  {
    id: 20871545,
    courseRegistrationId: 1100977,
    courseContentId: 19,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 19,
  },
  {
    id: 20871544,
    courseRegistrationId: 1100977,
    courseContentId: 20,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 20,
  },
  {
    id: 20871563,
    courseRegistrationId: 1100977,
    courseContentId: 21,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: 2,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: null,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 21,
  },
  {
    id: 20871564,
    courseRegistrationId: 1100977,
    courseContentId: 22,
    isCompleted: false,
    completeDate: null,
    contentSeconds: null,
    testId: null,
    testAnswer: null,
    testScore: null,
    testTries: null,
    evaluationId: 1,
    evaluationAnswer: null,
    evaluationOpinion: null,
    no: 22,
  },
]
