export const courseContents = [
  {
    id: 1,
    courseId: 1001,
    no: 1,
    type: 't',
    name: 'แบบทดสอบ Pre-test',
    content1: null,
    content2: null,
    minutes: null,
    testId1: 1,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 2,
    courseId: 1001,
    no: 2,
    type: 'c',
    name: 'บทที่ 1 วีดิโอแนะนำรายวิชา',
    content1: 'https://youtu.be/VFtVBSKY--U',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter01.mp4',
    minutes: 2,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 3,
    courseId: 1001,
    no: 3,
    type: 'c',
    name: 'บทที่ 2 ความหมายของคำว่า "ข้าราชการ"',
    content1: 'https://youtu.be/Eo1AWdwelBQ',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter02.mp4',
    minutes: 7,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 4,
    courseId: 1001,
    no: 4,
    type: 'c',
    name: 'บทที่ 3 ข้าราชการ หมายถึงใคร?',
    content1: 'https://youtu.be/awnHX86I0po',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter03.mp4',
    minutes: 2,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 5,
    courseId: 1001,
    no: 5,
    type: 'c',
    name: 'บทที่ 4 ข้าราชการควรวางตัวอย่างไร?',
    content1: 'https://youtu.be/OteXvn569kU',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter04.mp4',
    minutes: 10,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 6,
    courseId: 1001,
    no: 6,
    type: 'c',
    name: 'บทที่ 5 ข้าราชการกับบทบาทในวันนี้',
    content1: 'https://youtu.be/Qnx6_79jHe4',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter05.mp4',
    minutes: 7,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 7,
    courseId: 1001,
    no: 7,
    type: 'c',
    name: 'บทที่ 6 บทบาทข้าราชการกับประชาชน',
    content1: 'https://youtu.be/tWUzfVlAWRE',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter06.mp4',
    minutes: 11,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 8,
    courseId: 1001,
    no: 8,
    type: 'c',
    name: 'บทที่ 7 ฝันที่เป็นจริงกับความเป็นข้าราชการ',
    content1: 'https://youtu.be/7NN-3Ks4gLE',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter07.mp4',
    minutes: 3,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 9,
    courseId: 1001,
    no: 9,
    type: 'c',
    name: 'บทที่ 8 สิทธิประโยชน์ที่ข้าราชการพึงได้รับ',
    content1: 'https://youtu.be/wAnGsTTLnQs',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter08.mp4',
    minutes: 2,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 10,
    courseId: 1001,
    no: 10,
    type: 'c',
    name: 'บทที่ 9 เงินเดือน สวัสดิการ',
    content1: 'https://youtu.be/eyO-_GLUZCM',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter09.mp4',
    minutes: 4,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 11,
    courseId: 1001,
    no: 11,
    type: 'c',
    name: 'บทที่ 10 การได้รับพระราชทานเกียรติยศ ค่าตอบแทน',
    content1: 'https://youtu.be/Zr6l94sN6g4',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter10.mp4',
    minutes: 6,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 12,
    courseId: 1001,
    no: 12,
    type: 'c',
    name: 'บทที่ 11 ความแตกต่างระหว่างข้าราชการและเอกชน',
    content1: 'https://youtu.be/Di6VhAvBwgo',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter11.mp4',
    minutes: 9,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 13,
    courseId: 1001,
    no: 13,
    type: 'c',
    name: 'บทที่ 12 การแต่งกายตามพิธี พระราชพิธีและรัฐพิธี',
    content1: 'https://youtu.be/-ZkunelscbM',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter12.mp4',
    minutes: 6,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 14,
    courseId: 1001,
    no: 14,
    type: 'c',
    name: 'บทที่ 13 การแต่งกายตามพิธี พระราชพิธีและรัฐพิธี (ต่อ)',
    content1: 'https://youtu.be/x02Txp0-9pM',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter13.mp4',
    minutes: 5,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 15,
    courseId: 1001,
    no: 15,
    type: 'c',
    name: 'บทที่ 14 การปฏิบัติตัวร่วมพิธี พระราชพิธีและรัฐพิธี',
    content1: 'https://youtu.be/RmuLe7gV2Jg',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter14.mp4',
    minutes: 7,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 16,
    courseId: 1001,
    no: 16,
    type: 'c',
    name: 'บทที่ 15 การปฏิบัติตัวร่วมพิธี พระราชพิธีและรัฐพิธี (ต่อ)',
    content1: 'https://youtu.be/vAHy0rZ06w8',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter15.mp4',
    minutes: 5,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 17,
    courseId: 1001,
    no: 17,
    type: 'c',
    name: 'บทที่ 16 การเป็นข้าราชการ "คุณค่าในการเป็นข้าราชการ"',
    content1: 'https://youtu.be/9PauN9YTCcA',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter16.mp4',
    minutes: 7,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 18,
    courseId: 1001,
    no: 18,
    type: 'c',
    name: 'บทที่ 17 การเป็นข้าราชการ "คุณค่าในการเป็นข้าราชการ" (ต่อ)',
    content1: 'https://youtu.be/wLoWO8u_ZjY',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter17.mp4',
    minutes: 2,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 19,
    courseId: 1001,
    no: 19,
    type: 'c',
    name: 'บทที่ 18 ความภาคภูมิใจ เมื่อเกษียณอายุราชการ',
    content1: 'https://youtu.be/H4rkvoMH71s',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter18.mp4',
    minutes: 7,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 20,
    courseId: 1001,
    no: 20,
    type: 'c',
    name: 'บทที่ 19 การเป็นข้าราชการ "บทส่งท้าย"',
    content1: 'https://youtu.be/QgtrZ1vPO7I',
    content2:
      'https://learningportal.ocsc.go.th/content/video/NOF001/NOF001-chapter19.mp4',
    minutes: 3,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 21,
    courseId: 1001,
    no: 21,
    type: 't',
    name: 'แบบทดสอบ Post-test',
    content1: null,
    content2: null,
    minutes: null,
    testId1: 2,
    testId2: null,
    testId3: null,
    evaluationId: null,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
  {
    id: 22,
    courseId: 1001,
    no: 22,
    type: 'e',
    name: 'แบบประเมินรายวิชา',
    content1: null,
    content2: null,
    minutes: null,
    testId1: null,
    testId2: null,
    testId3: null,
    evaluationId: 1,
    course: null,
    evaluation: null,
    testId1Navigation: null,
    testId2Navigation: null,
    testId3Navigation: null,
    ocscContentView: [],
    ocscContentViewX: [],
  },
]
