export const courseRegistrations = [
  {
    id: 32148,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 136,
    courseRoundName: '2565/1',
    courseStart: '2021-11-25T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2021-12-16T00:47:09',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1016,
    code: 'DS06',
    name: 'Microsoft Office Excel 2016',
    categoryId: 4,
    learningObjective:
      'ผู้เรียนมีความรู้ ความเข้าใจ เกี่ยวกับการใช้งาน Microsoft Office\nExcel 2016 และ 2019',
    learningTopic:
      '<ol>\n<li>การทำสูตรคำนวณอายุงาน อายุราชการ</li>\n<li>การนำเสนอข้อมูลในรูปแบบแผนที่สามมิติ</li>\n<li>การแยกช้อมูลออกเป็นคอลัมน์ และการรวมข้อมูล</li>\n<li>การทำ Excel พูดภาษาอังกฤษ และคำอ่านตัวเลข</li>\n<li>การนำเสนอข้อมูลด้วย Conditional Formatting</li>\n<li>การวิเคราะข้อมูลด้วย Chart</li>\n<li>การใช้คำสั่ง if และการ filter ขัอมูล</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/D06.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 35691,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 126,
    courseRoundName: '2565/1',
    courseStart: '2021-11-25T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2021-12-17T12:08:02',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1006,
    code: 'KD06',
    name: 'วินัยและจรรยาข้าราชการ',
    categoryId: 1,
    learningObjective:
      '<ol>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายความหมาย ความสำคัญและจุดมุ่งหมายของวินัยและการปฏิบัติตามบทบัญญัติเรื่องวินัยได้</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายเจตนารมณ์ บทบัญญัติวินัยข้าราชการข้อกำหนด พฤติกรรมที่พึงประสงค์ การปฏิบัติตามข้อกำหนดได้</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายเรื่องเสริมสร้างและพัฒนาให้ข้าราชการมีวินัยและป้องกันมิให้ข้าราชการกระทำผิดวินัยได้</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายเรื่องโทษของการกระทำผิดวินัยข้าราชการและโทษทางวินัยได้</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายเรื่องการอุทธรณ์ขอความเป็นธรรมเมื่อถูกดำเนินการทางวินัยได้</li>\n</ol>\n\n<span style="color:red">ถ้าต้องการลงทะเบียนเรียนหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่ ให้ลงทะเบียนหลักสูตร จะได้รายวิชาทั้งหมดโดยอัตโนมัติ การลงทะเบียนเรียนทีละรายวิชา ไม่ถือว่าเป็นการลงทะเบียนเรียนในหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่ ต้องการลงทะเบียนหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่</span>\n<a href="https://learningportal.ocsc.go.th/learningspace/curriculums/1001" style="text-decoration: none">คลิกที่นี่</a>',
    learningTopic:
      '<ol>\n<li>"วินัยข้าราชการพลเรือน คือแบบแผนความประพฤติ ที่กำหนดให้ข้าราชการพลเรือนควบคุมตนเองและควบคุมผู้อยู่ใต้บังคับบัญชาให้ประพฤติดี ละเว้นการประพฤติปฏิบัติในทางไม่ชอบ ไม่ควร ความสำคัญ วินัยข้าราชการพลเรือน เป็นปัจจัยสำคัญที่จะช่วยให้การปฏิบัติราชการมีประสิทธิภาพ วินัยจึงมีความสำคัญต่อราชการเป็นส่วนรวมและต่อตัวข้าราชการ จุดมุ่งหมาย เพื่อประโยชน์ของทางราชการ เพื่อความเจริญ ความสงบเรียบร้อยของราชการเพื่อให้ราชการดำเนินไปด้วยดี มีประสิทธิภาพ ข้อกำหนดวินัย พระราชบัญญัติระเบียบข้าราชการพลเรือน พ.ศ. 2551 หมวด 6 วินัยและการรักษาวินัย ได้บัญญัติข้อกำหนดวินัยให้ข้าราชการพลเรือนยึดถือเป็นแบบแผนในการควบคุมความประพฤติ"</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K06.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 1098103,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 408,
    courseRoundName: '2566/1',
    courseStart: '2023-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2023-01-04T11:30:33',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1117,
    code: 'KD31',
    name: 'จุดมุ่งหมายของวินัยข้าราชการพลเรือนและบทบาทของผู้ดำเนินการทางวินัย',
    categoryId: 1,
    learningObjective:
      '<ol><li>ผู้เรียน เข้าใจ และสามารถอธิบายความหมายของวินัย และจุดมุ่งหมายของวินัย ได้</li><li>ผู้เรียนเข้าใจ และสามารถจำแนกแนวทางการรักษาวินัย และสาเหตุของการกระทำผิดวินัยได้</li><li>ผู้เรียนเข้าใจ และสามารถอธิบายปรัชญาการดำเนินการทางวินัย และกระบวนการดังกล่าวในภาพรวมได้</li><li>ผู้เรียนเข้าใจ และสามารถอธิบายผู้ที่มีหน้าที่เกี่ยวข้องกับการดำเนินการทางวินัย และบทบาทของผู้ดำเนินการทางวินัยได้</li><li>ผู้เรียนเข้าใจ และสามารถอธิบายข้อควรคำนึงเรื่องวินัยและการดำเนินการทางวินัย</li></ol>',
    learningTopic:
      '<ol><li>ความหมายของวินัย จุดมุ่งหมายและขอบเขตของวินัยข้าราชการ</li><li>แนวทางการรักษาวินัย และสาเหตุของการกระทำผิดวินัย</li><li>ปรัชญาการดำเนินการทางวินัย และกระบวนการดำเนินการทางวินัย</li><li>ผู้ที่มีหน้าที่เกี่ยวข้องกับการดำเนินการทางวินัย และบทบาทของผู้ดำเนินการทางวินัย</li><li>ข้อควรคำนึงเรื่องวินัยและการดำเนินการทางวินัย</li></ol>',
    targetGroup: '<ol><li>บุคลากรภาครัฐ</li><li>บุคคลทั่วไป</li></ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/KD31.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 1100976,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 380,
    courseRoundName: '2566/1',
    courseStart: '2023-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2023-01-04T22:58:31',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1089,
    code: 'DS01',
    name: 'Data Visualization',
    categoryId: 4,
    learningObjective:
      '<ol>\n<li>วัตถุประสงค์และสาเหตุของการทำ Data Visualization ได้</li>\n<li>ยกตัวอย่างลักษณะของ Visualization ที่ดีได้</li>\n<li>ยกตัวอย่างวิธีการสร้าง Visualization ได้</li>\n<li>มาตรฐานของ Visualization ได้</li>\n<li>การนำเสนอ Visualization เพื่อการสื่อสารได้</li>\n<li>ประยุกต์ใช้การเตรียมข้อมูล การทำความสะอาด และการจัดทำ Data Visualization ได้</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>วัตถุประสงค์การทำ Visualization ลักษณะของ visualization ที่ดี และไม่ดี</li>\n<li>การสร้าง visualization แหล่งที่มาของข้อมูล ลักษณะของทั่วไปของ visualization ลักษณะของแผนภูมิ</li>\n<li>การสื่อสารด้วย Visualization การเล่าเรื่องด้วย Visualization การวิเคราะห์แผนภูมิ</li>\n<li>การเตรียมข้อมูล การทำความสะอาดข้อมูล การแสดงผล DataVisualization </li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/D01.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 1100977,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 301,
    courseRoundName: '2566/1',
    courseStart: '2023-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2023-01-04T23:01:19',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1001,
    code: 'MS03',
    name: 'การเป็นข้าราชการ',
    categoryId: 2,
    learningObjective:
      '<ol>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายสถานภาพของข้าราชการ สามารถวางตนได้อย่างถูกต้องเหมาะสม</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายบทบาทของข้าราชการกับประชาชน</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายสิทธิ และประโยชน์ที่ข้าราชการพึงได้รับ</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายการปฏิบัติตนในพิธี และพระราชพิธีต่างๆ ได้อย่างถูกต้องเหมาะสม</li>\n<li>เพื่อให้ผู้เรียนสามารถอธิบายถึงคุณค่าในการเป็นข้าราชการ และความภาคภูมิใจเมื่อเกษียณอายุราชการ</li>\n</ol>\n\n<span style="color:red">ถ้าต้องการลงทะเบียนเรียนหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่ ให้ลงทะเบียนหลักสูตร จะได้รายวิชาทั้งหมดโดยอัตโนมัติ การลงทะเบียนเรียนทีละรายวิชา ไม่ถือว่าเป็นการลงทะเบียนเรียนในหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่ ต้องการลงทะเบียนหลักสูตรฝึกอบรมข้าราชการบรรจุใหม่</span>\n<a href="https://learningportal.ocsc.go.th/learningspace/curriculums/1001" style="text-decoration: none">คลิกที่นี่</a>',
    learningTopic:
      '<ol>\n<li>สถานภาพของข้าราชการ และการวางตัวของข้าราชการ</li>\n<li>บทบาทของข้าราชการ</li>\n<li>สิทธิ และประโยชน์ที่ข้าราชการพึงได้รับ</li>\n<li>การปฏิบัติตนในพิธี และพระราชพิธีต่าง ๆ</li>\n<li>คุณค่าในการเป็นข้าราชการ และความภาคภูมิใจเมื่อเกษียณอายุราชการ</li>\n</ol>\n\n',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/M03.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 1100980,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 381,
    courseRoundName: '2566/1',
    courseStart: '2023-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2023-01-04T23:07:05',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1090,
    code: 'DS02',
    name: 'Data Visualization 2',
    categoryId: 4,
    learningObjective:
      '<ol>\n<li>เพื่อให้สามารถอธิบาย Data Visualization Essentials</li>\n<li>เพื่อให้สามารถอธิบาย Multidimensional Data Visualizations</li>\n<li>เพื่อให้สามารถอธิบาย Relational Data Visualizations</li>\n<li>เพื่อให้สามารถอธิบาย Geospatial Data Visualizations</li>\n<li>เพื่อให้สามารถอธิบาย Interactive Data Visualizations</li>\n<li>เพื่อให้สามารถอธิบาย Data Visualization Validations</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>DATA VISUALIZATION ESSENTIALS MULTIDIMENSIONAL DATA VISUALIZATIONS</li>\n<li>RELATIONAL DATA VISUALIZATIONS GEOSPATIAL DATA VISUALIZATIONS</li>\n<li>INTERACTIVE DATA VISUALIZATIONS</li>\n<li>DATA VISUALIZATION VALIDATIONS</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/D02.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 1101015,
    userId: '1909802321001',
    curriculumRegistrationId: null,
    courseRoundId: 423,
    courseRoundName: '2566/1',
    courseStart: '2023-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2023-01-04T23:36:43',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1132,
    code: 'LS06',
    name: 'ภาษามลายูถิ่นเบื้องต้น',
    categoryId: 5,
    learningObjective: 'Fundamental Bahasa Melayu',
    learningTopic:
      '<ol><li>เพื่อมีความรู้ความเข้าใจเกี่ยวกับความรู้ทั่วไปของภาษามลายูถิ่น</li><li>เพื่อมีความรู้ความเข้าใจเกี่ยวกับบทสนทนาของภาษามลายูถิ่นในชีวิตประจำวัน</li><li>เพื่อมีความรู้ความเข้าใจเกี่ยวกับคำศัพท์พื้นฐานที่ใช้ในชีวิตประจำวัน</li></ol>',
    targetGroup: '<ol><li>บุคลากรภาครัฐ</li><li>บุคคลทั่วไป</li></ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/LS06.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362311,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 625,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1040,
    code: 'KD52',
    name: 'การตลาด',
    categoryId: 1,
    learningObjective:
      '<ol>\n<li>เข้าใจความหมายของการตลาดและความจำเป็นในการมีความรู้ด้านการตลาดสำหรับภาคราชการ</li>\n<li>ชี้แจงโครงสร้างตลาดทางการแข่งขัน (Competitive Market Structure) ได้</li>\n<li>ชี้แจงส่วนผสมทางการตลาด (Marketing Mix) 4 Ps และ 4 Cs ได้</li>\n<li>ชี้แจงการวิเคราะห์ลูกค้าในระดับเบื้องต้นได้</li>\n<li>ชี้แจงการวิเคราะห์คู่แข่งในระดับเบื้องต้นได้</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>ความรู้เบื้องต้นเกี่ยวกับการตลาด</li>\n<li>สภาพแวดล้อมทางการตลาด</li>\n<li>กลยุทธ์ทางการตลาด</li>\n<li>การสร้างตราสินค้า</li>\n<li>การบริหารความสัมพันธ์ต่อลูกค้า</li>\n<li>การตลาดกับพลังของสถานที่จำหน่ายสินค้า</li>\n<li>พฤติกรรมของผู้บริโภค</li>\n<li>การวิจัยทางการตลาดเพื่อการตัดสินใจเชิงกลยุทธ์</li>\n<li>การสื่อสารการตลาดแบบบูรณาการ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K22.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362312,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 538,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1041,
    code: 'SL36',
    name: 'การบริหารเชิงกลยุทธ์',
    categoryId: 3,
    learningObjective:
      '<ol>\n<li>อธิบายความหมายและคุณประโยชน์ของการบริหารเชิงกลยุทธ์ได้</li>\n<li>อธิบายประวัติความเป็นมาและการเปลี่ยนแปลงแนวความคิดของการบริหารกลยุทธ์ได้</li>\n<li>บ่งชี้และอธิบายแนวทางการพัฒนากลยุทธ์ได้ (Strategic Formulation)</li>\n<li>บ่งชี้สามเหตุสำคัญที่ทำให้แผนกลยุทธ์ล้มเหลวได้</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>กระบวนการเชิงกลยุทธ์</li>\n<li>การวิเคราะห์สถานการณ์</li>\n<li>วิสัยทัศน์และพันธกิจขององค์กร</li>\n<li>การสร้างกลยุทธ์ให้ประสบความสำเร็จ</li>\n<li>กลยุทธ์และการปฏิบัติการอย่างมีประสิทธิภาพ</li>\n<li>การบริหารเชิงกลยุทธ์และภาวะผู้นำ</li>\n<li>การบริหารความเสี่ยง</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S36.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362313,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 626,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1042,
    code: 'KD51',
    name: 'การบริหารการปฏิบัติการ',
    categoryId: 1,
    learningObjective:
      '<ol>\n<li>อธิบายแนวคิดและประโยชน์ของการประเมินผลการปฏิบัติงานในองค์กรได้</li>\n<li>อธิบายการประเมินผลการปฏิบัติในทั้ง 3 ระดับได้ (กลยุทธ์ องค์กร และปฏิบัติ)</li>\n<li>บ่งชี้และอธิบายผลที่ต้องได้จากการประเมินผลไม่ว่าระดับใดได้ (Feedback, Motivation, Incentive)</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>ความเข้าใจพื้นฐานเกี่ยวกับการบริหารการปฏิบัติการ</li>\n<li>ระบบการประเมินผลการปฎิบัติงาน</li>\n<li>เป้าหมายและตัวชี้วัดผลการปฏิบัติงาน</li>\n<li>การวัดแบบสมดุลย์</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>\n',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K23.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362314,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 539,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1043,
    code: 'KD24',
    name: 'การบริหารทรัพยากรบุคคล',
    categoryId: 1,
    learningObjective:
      'เพื่อให้ผู้เรียนทราบถึงบทบาทของผู้จัดการด้านทรัพยากรบุคคล การวางแผนทรัพยากรเชิงกลยุทธ์ และการบริหารทรัพยากรบุคคลโดยมุ่งเน้นสมรรถนะ',
    learningTopic:
      '<ol>\n<li>บทบาทของผู้จัดการด้านทรัพยากรบุคคล</li>\n<li>การบริหารทรัพยากรบุคคลประจำวัน</li>\n<li>การวางแผนทรัพยากรเชิงกลยุทธ์</li>\n<li>การบริหารทรัพยากรบุคคลโดยมุ่งเน้นสมรรถนะ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K24.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362315,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 540,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1044,
    code: 'KD25',
    name: 'เศรษฐศาสตร์',
    categoryId: 1,
    learningObjective:
      '<ol>\n<li>บทบาทของผู้จัดการด้านทรัพยากรบุคคล</li>\n<li>อธิบายหลักการวิเคราะห์ทางเศรษฐศาสตร์ได้</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>ความรู้เบื้องต้นเกี่ยวกับการวิเคราะห์ทางเศรษฐกิจ</li>\n<li>เศรษฐศาสตร์จุลภาค</li>\n<li>เศรษฐศาสตร์มหาภาค</li>\n<li>เศรษฐศาสตร์ดิจิตอล</li>\n<li>เศรษฐศาสตร์ระหว่างประเทศ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K25.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362316,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 541,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1045,
    code: 'KD26',
    name: 'การบริหารองค์การ',
    categoryId: 1,
    learningObjective:
      "<ol>\n<li>อธิบายสาเหตุหลักที่องค์การต้องเผชิญในโลกยุคปัจจุบันและคาดว่าต้องเผชิญในอนาคต (Understand the Key Issue Facing Organizations Today and in the Future)</li>\n<li>อธิบายแนวคิดการจัดองค์การที่มุ่งเน้นหลักการให้บริการที่ประชาชนต้องการ (Customer is Paramount, Customer's Perception is All)</li>\n</ol>",
    learningTopic:
      '<ol>\n<li>การวิเคราะห์องค์การ</li>\n<li>องค์การในยุคเศรษฐกิจสมัยใหม่</li>\n<li>ภาวะวิกฤติในองค์การ</li>\n<li>การบริหารการเปลี่ยนแปลง</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K26.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362317,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 542,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1046,
    code: 'KD27',
    name: 'การเงิน',
    categoryId: 1,
    learningObjective:
      '<ol>\n<li>อธิบายความหมายและเทคนิคการวิเคราะห์ต้นทุนได้</li>\n<li>อธิบายความเชี่อมโยงของการคิดเชิงกลยุทธ์กับต้นทุน เพื่อให้องค์กรมีขีดความสามารถในการแข่งขันและพัฒนาอย่างยั่งยืน</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>การวิเคราะห์ต้นทุนและการคิดเชิงกลยุทธ์</li>\n<li>ความหมายเฉพาะด้านการบัญชี</li>\n<li>การคิดต้นทุนต่อหน่วย</li>\n<li>ผลลัพท์ทางการเงินกับกลยุทธ์ขององค์การ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K27.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362318,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 543,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1047,
    code: 'SL37',
    name: 'การบริหารโครงการ',
    categoryId: 3,
    learningObjective:
      '<ol>\n<li>อธิบายแนวคิดพื้นฐานของการบริหารโครงการได้</li>\n<li>อธิบายการจัดการโครงการในด้าน Flow of Power, System Life Cycle</li>\n<li>อธิบายบทบาทที่ PM ควรจะเป็นใน Phase ต่าง ๆ ของโครงการ</li>\n<li>บ่งชี้และอธิบายขั้นตอนในการแก้ปัญหา</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>บทบาทของผู้บริหารโครงการ</li>\n<li>การกำหนดระยะเวลาการดำเนินโครงการและงบประมาณ</li>\n<li>การบริหารความเสี่ยงในการดำเนินโครงการ</li>\n<li>การวางแผนและควบคุมการใช้ทรัพยากร</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S37.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362319,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 544,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1048,
    code: 'SL38',
    name: 'กลยุทธ์ด้านเทคโนโลยีสารสนเทศ',
    categoryId: 3,
    learningObjective:
      'รู้และเข้าใจระบบการทำงานขั้นพื้นฐานของคอมพิวเตอร์ ฮาร์ดแวร์ ซอฟต์แวร์ และระบบปฏิบัติการต่าง ๆ ได้อย่างถูกต้อง',
    learningTopic:
      '<ol>\n<li>ความรู้พื้นฐานเกี่ยวกับคอมพิวเตอร์, ระบบปฏิบัติการ และโปรแกรมคอมพิวเตอร์</li>\n<li>ความรู้พื้นฐานเกี่ยวกับระบบเครือข่าย และโทรคมนาคม</li>\n<li>ฐานข้อมูล</li>\n<li>การใช้คอมพิวเตอร์และเทคโนโลยีด้านเว็บไซต์</li>\n<li>การดำเนินธุรกิจทางอิเล็กทรอนิกส์</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S38.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362320,
    userId: '1909802321001',
    curriculumRegistrationId: 139263,
    courseRoundId: 545,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:30:30',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1049,
    code: 'SL39',
    name: 'ภาวะผู้นำ',
    categoryId: 3,
    learningObjective:
      '<ol>\n<li>สำรวจภาวการณ์เป็นผู้นำของตนเองได้</li>\n<li>มีความรู้ความเข้าใจในบทบาทและหน้าที่ของผู้นำที่ดี</li>\n<li>รู้จักรูปแบบของผู้นำที่พึงประสงค์</li>\n<li>สร้างภาวะผู้นำที่ดีให้กับตนเองได้อย่างเหมาะสม</li>\n</ol>',
    learningTopic:
      '<ol>\n<li>ผู้นำการเปลี่ยนแปลง</li>\n<li>การแก้ปัญหาเกี่ยวกับพนักงาน</li>\n<li>การจูงใจทีมงาน</li>\n<li>จริยธรรมสำหรับข้าราชการ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S39.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362321,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 528,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1030,
    code: 'SL30',
    name: 'การบริหารจัดการภาครัฐแนวใหม่',
    categoryId: 3,
    learningObjective:
      ' โมดูลนี้จะนำเสนอเนื้อหาเกี่ยวกับการจัดโครงสร้างและระบบบริหารราชการแผ่นดินของประเทศไทย การจัดโครงสร้างและระบบบริหารราชการแผ่นดินของประเทศไทย ความสัมพันธ์ระหว่างฝ่ายนิติบัญญัติและฝ่ายบริหารองค์กรอิสระตามรัฐธรรมนูญ ความสัมพันธ์ระหว่างผู้บริหารราชการแผ่นดินฝ่ายการเมืองและข้าราชการประจำ การจัดระเบียบบริหารราชการส่วนกลาง ส่วนภูมิภาค ส่วนท้องถิ่น รัฐวิสาหกิจองค์กรมหาชน และหน่วยงานของรัฐอย่างอื่น ระบบและกระบวนการทางงบประมาณระบบข้าราชการพลเรือนและพนักงานราชการ แนวคิดพื้นฐานเกี่ยวกับการปฏิรูปบริหารภาครัฐ เหตุผลความจำเป็นในการเปลี่ยนแปลงและการปฏิรูประบบบริหารงานภาครัฐ แนวความคิดพื้นฐานเกี่ยวกับการปฏิรูประบบบริหารงานภาครัฐ การปฏิรูประบบบริหารระบบบริหารงานภาครัฐ Public Sector Reform ภาพรวมของการปฏิรูป การปฏิรูประบบราชการในประเทศไทย ระบบข้าราชการพลเรือนไทย คณะกรรมาธิการข้าราชการพลเรือน (ก.พ) อำนาจหน้าที่ของคณะกรรมการข้าราชการพลเรือน นโยบายการบริหารทรัพยากรบุคคล ราชการใสสะอาด การปรับปรุงระบบจำแนกตำแหน่งและค่าตอบแทน พ.ร.บ. ระเบียบข้าราชการพลเรือน พ.ศ. 2551 บทบาท ก.พ. และสำนักงาน ก.พ. การปฏิรูประบบราชการในประเทศไทย การปฏิรูประบบราชการในประเทศไทย (1) : การปฏิรูประบบราชการในประเทศไทย ภาพรวมของการปฏิรูประบบราชการในประเทศไทยที่ผ่านมา รายละเอียด แนวทาง และมาตรการเกี่ยวกับการปฏิรูประบบราชการของไทยที่ผ่านมา การปฏิรูประบบราชการในประเทศไทย (2) : ยุทธศาสตร์การพัฒนาระบบราชการไทยในปัจจุบัน หลักการตามมาตรา 3/1 แห่งพระราชบัญญัติระเบียบบริหารราชแผ่นดิน พ.ศ. 2545 พระราชกฤษฎีกาว่าด้วยหลักเกณฑ์และการบริหารกิจการบ้านเมืองที่ดี พ.ศ. 2546 แนวทางการพัฒนาระบบราชการ แนวทางในการพัฒนาระบบ ผลการพัฒนาระบบราชการไทย พ.ศ. 2546-2550',
    learningTopic:
      '<ol>\n<li>การจัดโครงสร้างและระบบบริหารราชการแผ่นดินของประเทศไทย</li>\n<li>แนวคิดพื้นฐานเกี่ยวกับการปฏิรูปบริหารภาครัฐ</li>\n<li>การปฏิรูประบบราชการในต่างประเทศ</li>\n<li>การปฏิรูประบบราชการในประเทศไทย</li>\n<li>ยุทธศาสตร์การพัฒนาระบบราชการไทยในปัจจุบัน</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S30.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362322,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 529,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1031,
    code: 'MS09',
    name: 'นโยบายสาธารณะ',
    categoryId: 2,
    learningObjective:
      'ในโมดุลนี้จะกล่าวถึงความหมายของนโยบายสาธารณะ องค์ประกอบของนโยบายสาธารณะ ขั้นตอนการก่อตัวของนโยบาย ขั้นตอนการกำหนดนโยบาย ขั้นตอนการนำนโยบายไปปฏิบัติ ขั้นตอนการประเมินผลนโยบาย ขั้นตอนการต่อเนื่อง การทดแทนและการสิ้นสุดนโยบาย รัฐธรรมนูญแห่งราชอาณาจักรไทย พ.ศ. 2550 กับนโยบายของรัฐบาลและการนำไปสู่การปฏิบัติแผนการบริหารราชการแผ่นดิน ตัวอย่างของกระทรวงกับนโยบายสาธารณะ',
    learningTopic:
      '<ol>\n<li>นิยาม ความหมาย นโยบายสาธารณะ</li>\n<li>วงจรชีวิตของนโยบายสาธารณะ</li>\n<li>รัฐธรรมนูญและนโยบายสาธารณะ</li>\n<li>นโยบายของรัฐบาลและการนำไปสู่การปฏิบัติ</li>\n<li>กระทรวงกับนโยบายสาธารณะ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/M09.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362323,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 530,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1032,
    code: 'SL31',
    name: 'การบริหารจัดการเชิงกลยุทธ์และการวัดผลงาน',
    categoryId: 3,
    learningObjective:
      'ศึกษาแนวคิดและแนวทางในการกำหนดยุทธศาสตร์ การนำยุทธศาสตร์ไปสู่การปฏิบัติ การวัดผลทางการปฏิบัติงานด้วยการกำหนดตัวชี้วัด การพัฒนาตัวชี้วัดระดับองค์การ การถ่ายทอดตัวชี้วัดไปสู่ระดับหน่วยงานและระดับบุคคลเพื่อผลการปฏิบัติงานที่ดี',
    learningTopic:
      '<ol>\n<li>การบริหารจัดการเชิงกลยุทธ์</li>\n<li>การนำแผนยุทธศาสตร์ไปสู่การปฏิบัติ</li>\n<li>การวัดผลงานและกรณีต่างๆ</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S31.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362324,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 531,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1033,
    code: 'SL32',
    name: 'องค์การและการจัดการ',
    categoryId: 3,
    learningObjective:
      'องค์การและการจัดการ (Organization and Management) นำเสนอเนื้อหาครอบคลุมประเด็นที่สำคัญในการจัดการองค์การ ทฤษฎีองค์การโดยสังเขป โครงสร้างองค์การ ภาวะผู้นำ สภาพแวดล้อมขององค์การ วัฒนธรรมองค์การ และการเปลี่ยนแปลงองค์การ ',
    learningTopic:
      '<ol>\n<li>ผลลัพธ์ขององค์การ (The Outcomes of Organization)</li>\n<li>ทฤษฎีองค์การ (Organizational Theory)</li>\n<li>การออกแบบและโครงสร้างองค์การ (Organization Structure and Design)</li>\n<li>ภาวะผู้นำและการจัดการ (Leadership and Management)</li>\n<li>สภาพแวดล้อมองค์การ (Organization Environment)</li>\n<li>วัฒนธรรมองค์การ (Organization Culture)</li>\n<li>องค์การและการเปลี่ยนแปลง (Organization and Change)</li> \n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S32.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362325,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 532,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1034,
    code: 'KD19',
    name: 'การบริหารทุนมนุษย์',
    categoryId: 1,
    learningObjective:
      'นำเสนอแนวคิดและพัฒนาการเกี่ยวกับการบริหารงานบุคคลที่ต่อมาพัฒนาเป็นแนวคิดการบริหารทรัพยากรมนุษย์ การบริหารทรัพยากรมนุษย์ในระบบราชการไทย  การบริหารทรัพยากรมนุษย์ในเชิงกลยุทธ์ ปัญหา และผลกระทบจากการเปลี่ยนแปลง รวมทั้งการพัฒนาทรัพยากรมนุษย์เพื่อการพัฒนาที่ยั่งยืน การบริหารและการวัดผลทุนมนุษย์  การเชื่อมโยงทุนมนุษย์กับกลยุทธ์ธุรกิจ',
    learningTopic:
      '<ol>\n<li>แนวคิดการบริหารงานบุคคลสู่การบริหารทรัพยากรมนุษย์และทุนมนุษย์</li>\n<li>การบริหารทรัพยากรมนุษย์ในระบบราชการไทย</li>\n<li>การบริหารเชิงกลยุทธ์และการบริหารทรัพยากรมนุษย์เชิงกลยุทธ์</li>\n<li>การออกแบบและการวิเคราะห์งาน</li>\n<li>การวางแผนทรัพยากรมนุษย์</li>\n<li>การสรรหาและการคัดเลือก</li>\n<li>การฝึกอบรมและพัฒนา</li>\n<li>การบริหารผลการปฏิบัติงาน</li>\n<li>การจ่ายค่าตอบแทน</li>\n<li>แรงงานสัมพันธ์</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K19.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362326,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 533,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1035,
    code: 'SL33',
    name: 'การออกแบบกระบวนการใหม่ และเทคโนโลยีสารสนเทศ',
    categoryId: 3,
    learningObjective:
      'ศึกษาแนวคิดและแนวทางการออกแบบกระบวนการใหม่ และเทคโนโลยีสารสนเทศ การออกแบบโปรแกรม การศึกษาระบบคอมพิวเตอร์ ตั้งแต่โครงสร้างของส่วนประกอบต่างๆ ของคอมพิวเตอร์ ระบบปฏิบัติการ โครงสร้างข้อมูล และขั้นตอนการทำงานต่างๆ การเก็บข้อมูลและประมวลผล การจัดระเบียบแฟ้มข้อมูล การศึกษาระบบข้อมูล และฐานข้อมูล รวมถึงระบบเครือข่ายการสื่อสาร และการพัฒนาระบบสารสนเทศ เพื่อนำไปใช้เป็นเครื่องมือในการปรับปรุง การทำงานและการพัฒนาหน่วยงาน ',
    learningTopic:
      '<ol>\n<li>แนวคิดพื้นฐานการบริหาร การออกแบบกระบวนการ และเทคโนโลยีสารสนเทศ</li>\n<li>ระบบคอมพิวเตอร์</li>\n<li>ข้อมูล และการจัดเก็บข้อมูล</li>\n<li>ระบบเครือข่ายการสื่อสาร</li>\n<li>การพัฒนาระบบสารสนเทศขององค์กร</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S33.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362327,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 534,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1036,
    code: 'KD20',
    name: 'การบัญชีและการจัดการทางการเงิน',
    categoryId: 1,
    learningObjective:
      'นำเสนอเนื้อหาเกี่ยวกับประวัติความเป็นมา ประโยชน์และความสำคัญ แนวคิดทฤษฎีหลักการพื้นฐานที่สำคัญทางการบัญชีและการเงิน ตัวอย่างการบัญชีและการเงินในภาคปฏิบัติทั้งภาคเอกชน กิจการซื้อ-ขายสินค้า กิจการอุตสาหกรรม และภาครัฐ สำหรับผู้เริ่มต้นอันเป็นการปูพื้นฐานทางการบัญชีและการเงินที่สำคัญเพื่อนำไปประยุกต์ในภาคปฏิบัติในการทำงาน การตัดสินใจทางการบริหาร หรือเพื่อการนำความรู้ไปต่อยอดเพื่อการศึกษาในระดับสูงต่อไป',
    learningTopic:
      '<ol>\n<li>การบัญชี : ภาคทฤษฎี</li>\n<li>การบัญชี : ภาคปฏิบัติ</li>\n<li>การจัดการทางการเงิน : ภาคการใช้ประโยชน์เพื่อการตัดสินใจทางการบริหาร</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K20.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362328,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 535,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:14',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1037,
    code: 'KD21',
    name: 'กฎหมายมหาชนภายใต้รัฐธรรมนูญแห่งราชอาณาจักรไทย พ.ศ. 2560',
    categoryId: 1,
    learningObjective:
      'เพื่อให้ผู้เรียนทราบถึงกฎหมายมหาชนภายใต้รัฐธรรมนูญแห่งราชอาณาจักรไทย พ.ศ. 2560',
    learningTopic:
      '<ol>\n<li>กฎหมายเพื่อรักษาความยุติธรรม</li>\n<li>รัฐธรรมนูญแห่งราชอาณาจักรไทย พุทธศักราช 2560 มาตรา 77</li>\n<li>การแบ่งแยกระหว่างกฎหมายมหาชนและกฎหมายเอกชน</li>\n<li>กฎหมายมหาชนในยุกกรีก โรมัน และยุคกลาง</li>\n<li>กฎหมายมหาชนยุคปัจจุบันเครื่องมือสร้างความเป็นธรรมในสังคม</li>\n<li>กฎหมายมหาชน</li>\n<li>รัฐ</li>\n<li>กฎหมายรัฐธรรมนูญ และกฎหมายปกครอง</li>\n<li>การบริหารราชการแผ่นดิน</li>\n<li>ความชอบด้วยกฎหมายกับการบริหารราชการแผ่นดิน</li>\n<li>หลักเกณฑ์สำคัญในการจัดทำบริการสาธารณะ</li>\n<li>องค์กรที่จัดทำบริการสาธารณะ</li>\n<li>วิวัฒนาการของทฤษฎีบริการสาธารณะ</li>\n<li>กฎหมายวิธีปฏิบัติราชการทางปกครอง</li>\n<li>สัญญาทางปกครอง</li>\n<li>ความรับผิดทางกฎหมายอันเกิดจากการบริหาร</li>\n<li>กฎหมายเพื่อประโยชน์สุขของประชาชน</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/K21.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362329,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 536,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:15',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1038,
    code: 'SL34',
    name: 'การจัดการความสัมพันธ์ระหว่างหน่วยงานของรัฐและภาคส่วนอื่นของสังคม',
    categoryId: 3,
    learningObjective:
      'นำเสนอเนื้อหาเกี่ยวกับการจัดระเบียบราชการแผ่นดินโดยสังเขปโดยอธิบายแยกย่อยเป็นส่วนของระเบียบบริหารราชการส่วนกลาง ส่วนภูมิภาค และส่วนท้องถิ่น นอกจากนี้ยังรวมถึงเนื้อหาในส่วนของความสัมพันธ์ระหว่างหน่วยงานของรัฐ ความสัมพันธ์ระหว่างหน่วยงานของรัฐกับภาคเอกชน ความสัมพันธ์ระหว่างหน่วยงานของรัฐกับประชาชน และภาคประชาสังคม รวมทั้งเนื้อหาในส่วนขององค์ประกอบของการปกครองตามระบอบประชาธิปไตย  ',
    learningTopic:
      '<ol>\n<li>การจัดระเบียบบริหารราชการแผ่นดิน</li>\n<li>ความสัมพันธ์ระหว่างรัฐต่อรัฐ</li>\n<li>ความสัมพันธ์ระหว่างหน่วยงานภาครัฐกับภาคเอกชน</li>\n<li>ความสัมพันธ์ระหว่างรัฐกับประชาชน</li>\n<li>ความสัมพันธ์ระหว่างรัฐกับภาคประชาสังคม</li>\n<li>องค์ประกอบของแนวคิดเสรีประชาธิปไตย</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S34.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
  {
    id: 2362330,
    userId: '1909802321001',
    curriculumRegistrationId: 139264,
    courseRoundId: 537,
    courseRoundName: '2567/1',
    courseStart: '2024-01-01T00:00:00',
    courseEnd: '3000-01-01T00:00:00',
    registrationDate: '2024-02-11T05:46:15',
    satisfactionScore: null,
    isCompleted: false,
    completeDate: null,
    courseId: 1039,
    code: 'SL35',
    name: 'นโยบายสาธารณะและประเด็นร่วมสมัยในการกำหนด/บริหารนโยบาย',
    categoryId: 3,
    learningObjective:
      'เพื่อให้ทราบถึงแนวทาง วิธีการศึกษานโยบายสาธารณะ การจัดกลุ่มภารกิจนโยบายสาธารณะ และประเด็นร่วมสมัยในการกำหนด/บริหารนโยบาย ',
    learningTopic:
      '<ol>\n<li>ความหมายของนโยบายสาธารณะ</li>\n<li>แนวทาง/วิธีการศึกษานโยบายสาธารณะ</li>\n<li>ประเภทของนโยบายสาธารณะ</li>\n<li>กระบวนการของนโยบายและกระบวนการในการแก้ไขปัญหา</li>\n<li>การจัดกลุ่มภารกิจนโยบายสาธารณะ</li>\n<li>ประเด็นร่วมสมัยของนโยบายสาธารณะ</li>\n<li>บทนำและเศรษฐกิจพอเพียง</li>\n<li>ยุทธศาสตร์อยู่ดีมีสุข</li>\n<li>วาระแห่งชาติด้านจริยธรรม ธรรมาภิบาล การป้องกันทุจริต และประพฤติมิชอบ</li>\n<li>FTA</li>\n<li>ผลพวงของการพัฒนาเศรษฐกิจ</li>\n<li>มิติความเหลี่อมล้ำกับการจัดสรรทรัพยากร</li>\n<li>ผลกระทบด้านเศรษฐกิจ การเมืองของความเหลื่อมล้ำทางเศรษฐกิจ</li>\n<li>สาเหตุของความเหลื่อมล้ำทางเศรษฐกิจ</li>\n<li>แนวทางการแก้ปัญหา</li>\n</ol>',
    targetGroup: '<ol>\n<li>บุคลากรภาครัฐ</li>\n<li>บุคคลทั่วไป</li>\n</ol>',
    assessment: 'ทำแบบทดสอบหลังเรียนได้ตั้งแต่ 60 % ขึ้นไป',
    thumbnail:
      'https://learningportal.ocsc.go.th/content/images/courses/ocsc/S35.jpg',
    seqFlow: false,
    hideStartEnd: false,
  },
]
