export const EvaluationItems = [
  {
    id: 1,
    evaluationId: 1,
    no: 1,
    question: 'หัวข้อบทเรียนครบถ้วนตามวัตถุประสงค์',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 2,
    evaluationId: 1,
    no: 2,
    question:
      'การเชื่อมโยงเข้าสู่บทเรียนแต่ละหัวข้อได้ถูกต้องตรงตามหัวข้อวิชาที่ระบุไว้',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 3,
    evaluationId: 1,
    no: 3,
    question: 'เนื้อหาในรายวิชาเข้าใจได้ง่าย ไม่ยุ่งยากซับซ้อน',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 4,
    evaluationId: 1,
    no: 4,
    question: 'วิทยากร/ผู้บรรยาย อธิบายเนื่อหาได้ตรงตามหัวข้อและวัตถุประสงค์',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 5,
    evaluationId: 1,
    no: 5,
    question: 'การแสดงผลของเนื้อหาวิชา และ VDO มีความสอดคล้องสัมพันธ์กัน',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 6,
    evaluationId: 1,
    no: 6,
    question: 'กราฟิกหรือสื่อประกอบบทเรียนมีความสวยงาม',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 7,
    evaluationId: 1,
    no: 7,
    question: 'คุณภาพของ VDO บทเรียน',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 8,
    evaluationId: 1,
    no: 8,
    question: 'บทเรียนมีความน่าสนใจ',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 9,
    evaluationId: 1,
    no: 9,
    question: 'ส่งเสริมให้เรียนรู้ได้ดียิ่งขึ้น',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 10,
    evaluationId: 1,
    no: 10,
    question: 'ท่านมีความรู้ในหัวข้อวิชาที่เรียนรู้ในระดับใด',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
  {
    id: 11,
    evaluationId: 1,
    no: 11,
    question:
      'ความพึงพอใจในภาพรวมทั้งหมดของบทเรียนอิเล็กทรอนิกส์ (OCSC Learning Space)',
    choice1: 'มากที่สุด',
    choice2: 'มาก',
    choice3: 'ปานกลาง',
    choice4: 'น้อย',
    choice5: 'น้อยที่สุด',
    evaluation: null,
  },
]
