export const testItems = [
  {
    id: 959,
    testId: 59,
    no: 1,
    question: 'ข้อใดไม่ใช่รูปแบบความสัมพันธ์ระหว่างฝ่ายนิติบัญญัติ',
    imgUrl: null,
    numChoices: 4,
    choice1: 'การเรียกประชุม ขยายเวลาประชุม และปิดประชุมสภา',
    imgUrl1: null,
    choice2: 'การแต่งตั้งปลัดกระทรวง',
    imgUrl2: null,
    choice3: 'การแต่งตั้งผู้นำฝ่ายค้านในสภา',
    imgUrl3: null,
    choice4: 'การแต่งตั้งประธานสภาและรองประธานสภา',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 2,
    test: null,
  },
  {
    id: 960,
    testId: 59,
    no: 2,
    question: 'ข้อใดเป็นหลักของการจัดโครงสร้างระบบบริหารราชการแผ่นดินของไทย',
    imgUrl: null,
    numChoices: 4,
    choice1: 'รัฐมีฐานะเป็นบุคคล',
    imgUrl1: null,
    choice2: 'แบ่งการบริหารโดยสภาผู้แทนราษฎร',
    imgUrl2: null,
    choice3: 'จัดโครงสร้างตามหลักประชาธิปไตย',
    imgUrl3: null,
    choice4: 'มีรูปแบบโครงสร้างแบบรวมศูนย์อำนาจ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 961,
    testId: 59,
    no: 3,
    question:
      'ข้อใดคือแนวคิดสำคัญของความสัมพันธ์ระหว่างผู้บริหารราชการแผ่นดินฝ่ายการเมืองกับข้าราชการ',
    imgUrl: null,
    numChoices: 4,
    choice1: 'แนวคิดการปรับปรุงระบบราชการที่ทันสมัย',
    imgUrl1: null,
    choice2: 'แนวคิดการบริหารงานแบบ CEO',
    imgUrl2: null,
    choice3: 'แนวคิดการจัดการบริหารแบบบูรณาการ',
    imgUrl3: null,
    choice4: 'แนวคิดการแยกการเมืองออกจากการบริหาร',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 962,
    testId: 59,
    no: 4,
    question: 'ช้อใดไม่ใช่หน่วยงานในกำกับของรัฐ',
    imgUrl: null,
    numChoices: 4,
    choice1: 'องค์การไม่แสวงผลกำไร (NGO)',
    imgUrl1: null,
    choice2: 'องค์การขนส่งมวลชนกรุงเทพ',
    imgUrl2: null,
    choice3: 'การไฟฟ้าส่วนภูมิภาค',
    imgUrl3: null,
    choice4: 'องค์การสื่อสารมวลชนแห่งประเทศไทย',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 963,
    testId: 59,
    no: 5,
    question:
      'ข้อใดเป็นเหตุผลที่ต้องมีความจำเป็นในการเปลี่ยนแปลงและปฏิรูประบบบริหารภาครัฐ',
    imgUrl: null,
    numChoices: 4,
    choice1: 'การเปลี่ยนแปลงของสังคมโลกด้านต่าง ๆ',
    imgUrl1: null,
    choice2: 'เนื่องจากเกิดการปฏิวัติอุตสาหกรรมเข้าสู่โลกเทคโนโลยี',
    imgUrl2: null,
    choice3: 'ต้องการให้ระบบราชการเข้มแข็งมากขึ้น',
    imgUrl3: null,
    choice4:
      'เกิดจากการที่รัฐเริ่มสร้างนโยบายการบริหารบ้านเมืองแนวใหม่ที่มีความจำเป็นต้องปรับปรุงระบบราชการ เพื่อให้มีความสอดคล้องกัน',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 964,
    testId: 59,
    no: 6,
    question: 'ข้อใดไม่เกี่ยวข้องกับการบริหารงานภาครัฐแนวใหม่',
    imgUrl: null,
    numChoices: 4,
    choice1: 'Jonathan Boston',
    imgUrl1: null,
    choice2: 'Christopher Hood',
    imgUrl2: null,
    choice3: 'R.A.W Rhoder',
    imgUrl3: null,
    choice4: 'John Adams',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 965,
    testId: 59,
    no: 7,
    question:
      'แนวคิดพื้นฐานที่สำคัญเกี่ยวกับการปฏิรูประบบบริหารงานภาครัฐที่กล่าวถึงในที่นี้มีกี่ตัวแบบ',
    imgUrl: null,
    numChoices: 4,
    choice1: '2 ตัวแบบ',
    imgUrl1: null,
    choice2: '3 ตัวแบบ',
    imgUrl2: null,
    choice3: '5 ตัวแบบ',
    imgUrl3: null,
    choice4: '6 ตัวแบบ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 966,
    testId: 59,
    no: 8,
    question: 'ทฤษฎีใดที่ไม่ได้กล่าวถึงในที่นี้',
    imgUrl: null,
    numChoices: 4,
    choice1: 'เศรษฐศาสตร์นีโอคลาสสิก',
    imgUrl1: null,
    choice2: 'ทฤษฎีทางเลือกสาธารณะ',
    imgUrl2: null,
    choice3: 'ทฤษฎีตัวการและตัวแทน',
    imgUrl3: null,
    choice4: 'ไม่มีข้อใดถูก',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 967,
    testId: 59,
    no: 9,
    question: 'ข้อใดไม่ใช่เทคนิควิธีการสำหรับการบริหารจัดการสมัยใหม่',
    imgUrl: null,
    numChoices: 4,
    choice1: 'การบริหารโดยเน้นการบริการเป็นหลัก',
    imgUrl1: null,
    choice2: 'การบริหารแบบมุ่งผลสัมฤทธิ์',
    imgUrl2: null,
    choice3: 'การบริหารโดยยึดวัตถุประสงค์',
    imgUrl3: null,
    choice4: 'การบริหารคุณภาพ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 968,
    testId: 59,
    no: 10,
    question: 'ข้อใดที่เป็นปัญหาข้อจำกัดประชาธิปไตยแบบตัวแทน',
    imgUrl: null,
    numChoices: 4,
    choice1: 'ความห่างไกล',
    imgUrl1: null,
    choice2: 'จำนวนประชากร',
    imgUrl2: null,
    choice3: 'จำนวนตัวแทน',
    imgUrl3: null,
    choice4: 'การแบ่งพื้นที่',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 969,
    testId: 59,
    no: 11,
    question: 'ข้อใดไม่เป็นแนวความคิดเกี่ยวกับประชาธิปไตยแนวทางใหม่',
    imgUrl: null,
    numChoices: 4,
    choice1: 'ชุมชนนิยม',
    imgUrl1: null,
    choice2: 'อนุรักษ์นิยม',
    imgUrl2: null,
    choice3: 'การรวมตัวกันของประชาชนอย่างสมัครใจ',
    imgUrl3: null,
    choice4: 'การปกครองระบอบสมบูรณาญาสิทธิราชเป็นระบอบที่ล้าสมัย',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 2,
    test: null,
  },
  {
    id: 970,
    testId: 59,
    no: 12,
    question: 'การบริหารงานภาครัฐแนวใหม่ได้รับอิทธิพลมาจากแนวคิดใดเป็นหลัก',
    imgUrl: null,
    numChoices: 4,
    choice1: 'การผสมผสานระหว่างเศรษฐศาสตร์และการบริหารจัดการสมัยใหม่',
    imgUrl1: null,
    choice2: 'การผสมผสานระหว่างรัฐศาสตร์และกฎหมายมหาชน',
    imgUrl2: null,
    choice3: 'การขัดการเชิงกลยุทธ์',
    imgUrl3: null,
    choice4: 'ข้อ ก. และ ข้อ ข. ถูก',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 971,
    testId: 59,
    no: 13,
    question: 'ข้อใดไม่ใช่ยุทธศาสตร์ของการปฏิรูประบบราชการในต่างประเทศ',
    imgUrl: null,
    numChoices: 4,
    choice1: 'ลดขนาดและตัดทอนงบประมาณ',
    imgUrl1: null,
    choice2: 'การปรับเปลี่ยนการทำงานให้ทันสมัย',
    imgUrl2: null,
    choice3: 'การปรับปรุงโครงสร้างองค์กร',
    imgUrl3: null,
    choice4: 'ใช่ทั้งหมด',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 972,
    testId: 59,
    no: 14,
    question: 'กลยุทธ์การปฏิรูปภาครัฐของฟินแลนด์คล้ายคลึงกับประเทศใดมากที่สุด',
    imgUrl: null,
    numChoices: 4,
    choice1: 'เดนมาร์ก',
    imgUrl1: null,
    choice2: 'อังกฤษ',
    imgUrl2: null,
    choice3: 'สวีเดน',
    imgUrl3: null,
    choice4: 'ฝรั่งเศส',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 3,
    test: null,
  },
  {
    id: 973,
    testId: 59,
    no: 15,
    question:
      'การปฏิรูปการบริหารงานบุคคลระบบราชการในประเทศไทยเริ่มขึ้นในสมัยรัชกาลใด',
    imgUrl: null,
    numChoices: 4,
    choice1: 'รัชกาลที่ 5',
    imgUrl1: null,
    choice2: 'รัชกาลที่ 6',
    imgUrl2: null,
    choice3: 'รัชกาลที่ 7',
    imgUrl3: null,
    choice4: 'รัชกาลที่ 8',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 3,
    test: null,
  },
  {
    id: 974,
    testId: 59,
    no: 16,
    question: 'ข้อใดเป็นการจ่ายค่าตอบแทนและเงินรางวัลตามผลงาน',
    imgUrl: null,
    numChoices: 4,
    choice1: 'จ่ายตามผลสัมฤทธิ์ของงานแทนการจ่ายค่าตอบแทนตามหน้าที่เท่านั้น',
    imgUrl1: null,
    choice2: 'จ่ายตามหน้าที่ที่ได้รับมอบ',
    imgUrl2: null,
    choice3: 'จ่ายตามความขยันและระยะเวลาทำงาน',
    imgUrl3: null,
    choice4: 'จ่ายตามผลงานที่ชัดเจน',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 975,
    testId: 59,
    no: 17,
    question:
      'แผนยุทธศาสตร์การพัฒนาระบบราชการไทย พ.ศ. 2546 - 2550 มุ่งให้ความสำคัญเรื่องใด',
    imgUrl: null,
    numChoices: 4,
    choice1: 'พัฒนาศักยภาพด้านบุคลากรให้เท่าเทียมเกณฑ์สากล',
    imgUrl1: null,
    choice2:
      'พัฒนาคุณภาพการให้บริการ การปรับบทบาทภารกิจให้เหมาะสม การยกระดับขีดความสามารถและมาตรฐานการทำงานให้อยู่ในระดับสูงและเทียบเท่าเกณฑ์สากล',
    imgUrl2: null,
    choice3:
      'ยกระดับการให้บริการและการทำงาน ปรับปรุงรูปแบบการให้บริการให้มีรูปแบบเชิงบูรณาการ มุ่งสู่องค์การที่มีสมรรถนะสูง สร้างระบบกำกับตนเองที่ดี โปร่งใส มั่นใจ ตรวจสอบได้',
    imgUrl3: null,
    choice4:
      'ใช้ทรัพยากรอย่างคุ้มค่า สร้างโครงสร้างองค์กรให้เข้มแข็งเพื่อต่อรองการเปลี่ยนแปลงนโยบาย',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
  {
    id: 976,
    testId: 59,
    no: 18,
    question: 'ข้อใดเป็นเครื่องมือในการนำยุทธศาสตร์ไปปฏิบัติให้เกิดผล',
    imgUrl: null,
    numChoices: 4,
    choice1:
      'การผลักดันพระราชกฤษฎีกาว่าด้วยหลักเกณฑ์และการบริหารกิจการบ้านเมืองที่ดี พ.ศ. 2546',
    imgUrl1: null,
    choice2: 'การประกาศในกฎกระทรวงเรื่องการนำแผนยุทธศาสตร์มาใช้',
    imgUrl2: null,
    choice3: 'การจัดทำแผนปฏิบัติการ',
    imgUrl3: null,
    choice4: 'การร่วมเป็นเจ้าภาพพัฒนาระบบราชการ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 977,
    testId: 59,
    no: 19,
    question: 'ข้อใดเป็นการพัฒนาคุณภาพการให้บริการประชาชนที่ดีขึ้น',
    imgUrl: null,
    numChoices: 4,
    choice1: 'Call Center 1111',
    imgUrl1: null,
    choice2: 'การปรับราคารถโดยสาร',
    imgUrl2: null,
    choice3: 'สร้างสะพานข้ามแยก',
    imgUrl3: null,
    choice4: 'ปรับขึ้นเงินเดือนข้าราชการ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 1,
    test: null,
  },
  {
    id: 978,
    testId: 59,
    no: 20,
    question: 'ข้อใดไม่ใช่แนวทางในการพัฒนาระบบราชการให้เป็นระบบเปิด',
    imgUrl: null,
    numChoices: 4,
    choice1: 'การมีส่วนร่วมของประชาชน',
    imgUrl1: null,
    choice2: "การตรวจสอบภาคประชาชน (People's Audit)",
    imgUrl2: null,
    choice3: 'การสร้างเครือข่ายการพัฒนาระบบราช',
    imgUrl3: null,
    choice4: 'ถูกทุกข้อ',
    imgUrl4: null,
    choice5: null,
    imgUrl5: null,
    solution: 4,
    test: null,
  },
]
